### PR TITLE
RavenDB-3384 Making sure that index replacement takes place for precompu...

### PR DESCRIPTION
**Pull request by arekpalinski**
...ted indexes

### CODE REVIEW

**Comment by ayende** [comment]
Arek,
This now fails:

Raven.Tests.Indexes.IndexReplacementTest.ReplaceAfterNonStale [FAIL]
   Assert.True() Failure
   Stack Trace:
      c:\Work\ravendb\Raven.Tests\Indexes\IndexReplacement.cs(78,0): at
Raven.Tests.Indexes.IndexReplacementTest.Replace
AfterNonStale()


*Hibernating Rhinos Ltd  *

Oren Eini* l CEO l *Mobile: + 972-52-548-6969

Office: +972-4-622-7811 *l *Fax: +972-153-4-622-7811

**Comment by arekais** [comment]
Did it fail on your machine? I've just run it over 700 times and it always passes.

**Comment by ayende** [comment]
Yes, it did.

*Hibernating Rhinos Ltd  *

Oren Eini* l CEO l *Mobile: + 972-52-548-6969

Office: +972-4-622-7811 *l *Fax: +972-153-4-622-7811

**Comment by arekais** [comment]
Okay. I will try to reproduce that. However it's completely unrelated to the change made in this PR because the precomputed batch optimization isn't applied in this case.

**Comment by ayende** [comment]
It consistently failed for me when running the full build process.


*Hibernating Rhinos Ltd  *

Oren Eini* l CEO l *Mobile: + 972-52-548-6969

Office: +972-4-622-7811 *l *Fax: +972-153-4-622-7811

**Comment by arekais** [comment]
I'm able to reproduce that during the build process too - I'm investigating this.

**Comment by arekais** [comment]
Fixed here: https://github.com/ayende/ravendb/pull/2135

**Pull request merged**
