### PR TITLE
JsonConverterCache with locks to test.

### PR DESCRIPTION
**Pull request by redknightlois**

### CODE REVIEW

**Comment by ayende** [comment]
This is a thread static variable that you are locking.
You _cannot_ have task stealing switch on you mid operation.
That can only happen when you work with the TPL methods such as await, SetResult, etc.

**Comment by redknightlois** [comment]
The question behind is: Is that possible at all? If it is, we are just masking the problem. Did you try this version on the tests and find any NRE?

**Comment by ayende** [comment]
No, I didn't try it.
And the error wasn't because of threading issue.
The error was because you it was comparing two fast or two slow (it was NRE
isn't the comparer).

*Hibernating Rhinos Ltd  *

Oren Eini* l CEO l *Mobile: + 972-52-548-6969

Office: +972-4-622-7811 *l *Fax: +972-153-4-622-7811

**Comment by ayende** [comment]
it was NRE inside the comparer, sorry.

*Hibernating Rhinos Ltd  *

Oren Eini* l CEO l *Mobile: + 972-52-548-6969

Office: +972-4-622-7811 *l *Fax: +972-153-4-622-7811

**Comment by redknightlois** [comment]
Follow the code, you will see it is impossible. We only store Slow, and we always test with Fast therefore there is absolutely no chance we can compare both of the same. 

Check how the comparer is used in the dictionary code: https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Collections/Generic/Dictionary.cs
(CoreCLR is roughly the same as ReferenceSource). All comparisons happen between the function parameter and the internal... never between 2 internals. Not even resize uses a comparison between internal or external keys.

The error is an NRE. True! But that's why I am not convinced (at all). 

We have just masked the issue and it is going to come back to bite us, eventually. And the problem is that we wont be able to figure out why.

**Comment by ayende** [comment]
I'm absolutely sure that the code is right, and yet we had an NRE.
On the line when it compares the two values.
I'm not sure why that happens, but it did.

Is the virtual method call so expensive that we need to prevent it by that
much?

*Hibernating Rhinos Ltd  *

Oren Eini* l CEO l *Mobile: + 972-52-548-6969

Office: +972-4-622-7811 *l *Fax: +972-153-4-622-7811

**Comment by redknightlois** [comment]
Then you agree with me it is an heisenbug; and those are most of the times race condition based. Good thing is that the code is high-frequency, so it will appear in a couple of test runs if you machine is already capable of generating it. 

We can code it way faster without the virtual function. If after running the tests with the locked version we still get the NRE, I will PR a faster version of the comparer. But it is a moot point before ruling out threading. 

We need to be sure the problem is not in the threading, at the moment I am far unconvinced.

**Comment by redknightlois** [comment]
I will try to elaborate my hypotesis why it appears to works, but it is not. 

The JIT compiler is optimizing the hell out of the method, that is why with the virtual method you get 7% to 9% slower comparisons. 

When the method is not optimized we have a call operation that acts as a read memory barrier. Therefore, the JIT has to evict some of the already existing registers to make space to the fast-call. Adding the virtual method make it difficultier for the condition to happen but doesnr preclude it to happen; it just makes the window smaller. With less instructions + more accesses via registers the window for failure is bigger, therefore we see the NREs. 

Moreover, in this case we are actually able to see the NREs. My hypothesis of how the failure will look in the virtual case is that as we have different dictionaries, we can get a result from a different bucket in the second (specially when you have to deal with a collision, therefore double hashing). It is a pretty rare condition, but not impossible. But returning the wrong result can be catastrofic; say you get a converter for GUIDs instead of Json... good luck trying to repro the issue.

My worry is that havent been able to see it, it doesnt means that it is not there.

**Comment by ayende** [comment]
Okay, I've reset this, and we'll wait for it to happen again.

*Hibernating Rhinos Ltd  *

Oren Eini* l CEO l *Mobile: + 972-52-548-6969

Office: +972-4-622-7811 *l *Fax: +972-153-4-622-7811

**Pull request merged**
