### PR TITLE
Raven db 3023

### PR DESCRIPTION
**Pull request by ml054**

### CODE REVIEW

**Comment by ml054** [comment]
Please don't merge this PR yet. Looks like map timings are wrong + we put hatch into parallel blocks.

**Comment by ayende** [comment]
Okay, I'll wait for an update on this

*Hibernating Rhinos Ltd  *

Oren Eini* l CEO l *Mobile: + 972-52-548-6969

Office: +972-4-622-7811 *l *Fax: +972-153-4-622-7811



On Fri, Jan 9, 2015 at 4:27 PM, Marcin Lewandowski <notifications@github.com

**Comment by ml054** [comment]
Ok, this can be merged.

**Comment by ppekrol** [comment]
Marcin and Arek found a flaw and they are fixing it now. Please hold stable release till this is fixed.

**Pull request merged**
