### PR TITLE
Agressive Inlining and MemoryUtils optimizations.

### PR DESCRIPTION
**Pull request by redknightlois**
Check the mail I sent you.

### CODE REVIEW

**Comment by redknightlois** [comment]
Added a tryout of the optimization for the Default.Converters path. I mostly rule-out all the accesses to the costly calls from RavenDB. I haven't run an extensive battery of tests there yet, but wanted you to take a look to see if it makes sense.

**Comment by ayende** [comment]
Are we actually passing the actual converters array there?
We have many cases where we do this:


for (var i = Default.Converters.Length - 1; i >= 0; i--)
{
jsonSerializer.Converters.Insert(0, Default.Converters[i]);
}


So it won't be the same instance. See also: CreateDefaultJsonSerializer,
which has the same issue and is used extensively in our code.

Then again, that uses the serializer, which isn't using RavenJValue at all,
does it?

Also, see the small optimization to avoid alloc there.


*Hibernating Rhinos Ltd  *

Oren Eini* l CEO l *Mobile: + 972-52-548-6969

Office: +972-4-622-7811 *l *Fax: +972-153-4-622-7811

**Comment by redknightlois** [comment]
Line by line profiling shows a marked improvement even with that crude approach. I will look to see if there is something else going on

-----Original Message-----

**Comment by redknightlois** [comment]
There are only 2 locations. One is the CreateSerializer which we cannot optimize (at all) because we cannot predict its reference… I knew about that one because it showed in the profiling run under the JArray, JObject and JValue :) .

 

As long as we are using RavenJValue we have a performance network that “may” hit, with JValue all bets are off. 

 

 

From: Federico Lois [mailto:federico.lois@corvalius.com] 
Sent: martes, 13 de enero de 2015 17:59
To: ayende/ravendb
Subject: RE: [ravendb] Agressive Inlining and MemoryUtils optimizations. (#1798)

 

Line by line profiling shows a marked improvement even with that crude approach. I will look to see if there is something else going on

  _____

**Comment by ayende** [comment]
Yes, I think this is good for RavenJObject and friends, the rest is just
serializing mostly on the client side.

*Hibernating Rhinos Ltd  *

Oren Eini* l CEO l *Mobile: + 972-52-548-6969

Office: +972-4-622-7811 *l *Fax: +972-153-4-622-7811

**Pull request closed without merging**
