### PR TITLE
RavenDB-3746: Process OperationCanceledException from server to clien…

### PR DESCRIPTION
**Pull request by aviviadi**
…t as

StatusCode=RequestTimeout and Message=Request was canceled by the server
due to timeout

### CODE REVIEW

**Comment by ayende** [comment]
That is fine, but what we actually need to do for RavenDB-3746 is to start
sending heartbeats so the request will NOT time out.

*Hibernating Rhinos Ltd  *

Oren Eini* l CEO l *Mobile: + 972-52-548-6969

Office: +972-4-622-7811 *l *Fax: +972-153-4-622-7811

**Comment by aviviadi** [comment]
Ok, should I keep the above change too?

**Comment by ayende** [comment]
Yes

*Hibernating Rhinos Ltd  *

Oren Eini* l CEO l *Mobile: + 972-52-548-6969

Office: +972-4-622-7811 *l *Fax: +972-153-4-622-7811

**Comment by ayende** [comment]
But also include the actual timing information, the URL that was requested,
etc.

*Hibernating Rhinos Ltd  *

Oren Eini* l CEO l *Mobile: + 972-52-548-6969

Office: +972-4-622-7811 *l *Fax: +972-153-4-622-7811

**Pull request merged**
