### PR TITLE
RavenDB-3838

### PR DESCRIPTION
**Pull request by myarichuk**
TODO related misc fixes and refactorings

### CODE REVIEW

**Comment by ppekrol** [comment]
@myarichuk Can you fix whitespace? And if possible add issue # to commit messages? Use rebase for this.

**Comment by HibernatingRhinosServiceAccount** [comment]
Will fix.
About commit messages - is it not enough to include issue # at PR title?

On Sat, Dec 5, 2015 at 4:45 PM, Paweł Pekról <notifications@github.com>
wrote:

> @myarichuk <https://github.com/myarichuk> Can you fix whitespace? And if
> possible add issue # to commit messages? Use rebase for this.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ayende/ravendb/pull/2957#issuecomment-162200718>.
>



-- 
Best regards,



*Michael Yarichuk*

RavenDB Core Team

Tel: 972-4-6227811

Fax:972-153-4-6227811

Email : michael.yarichuk@hibernatingrhinos.com



*Raven**DB** paving the way to "Data Made Simple" http://ravendb.net/
<http://ravendb.net/>  *

**Comment by ppekrol** [comment]
Unfortunately no, because this information is not preserved in history.

**Comment by myarichuk** [comment]
reopening another PR with fixes

**Pull request closed without merging**
