### PR TITLE
RavenDB-3217 Let the user know how many steps a script took

### PR DESCRIPTION
**Pull request by ml054**

### CODE REVIEW

**Comment by ayende** [comment]
What changes did you make in Jint, and where are they?

**Comment by ppekrol** [comment]
Marcin, please send a PR here https://github.com/ppekrol/jint/tree/2.4.0-ravendb

**Comment by ml054** [comment]
Where should I send this PR?

**Comment by ayende** [comment]
Marcin, please send a PR here
https://github.com/ppekrol/jint/tree/2.4.0-ravendb

*Hibernating Rhinos Ltd  *

Oren Eini* l CEO l *Mobile: + 972-52-548-6969

Office: +972-4-622-7811 *l *Fax: +972-153-4-622-7811



On Thu, Apr 9, 2015 at 8:24 AM, Marcin Lewandowski <notifications@github.com

**Comment by ml054** [comment]
I've already pushed changes there without PR.

**Comment by ayende** [comment]
Okay

*Hibernating Rhinos Ltd  *

Oren Eini* l CEO l *Mobile: + 972-52-548-6969

Office: +972-4-622-7811 *l *Fax: +972-153-4-622-7811

**Comment by ml054** [comment]
Anything else I have to do to close this PR?

**Comment by ayende** [comment]
Making sure, the Jint dll was compiled in release mode, right?

*Hibernating Rhinos Ltd  *

Oren Eini* l CEO l *Mobile: + 972-52-548-6969

Office: +972-4-622-7811 *l *Fax: +972-153-4-622-7811



On Thu, Apr 9, 2015 at 3:53 PM, Marcin Lewandowski <notifications@github.com

**Comment by ml054** [comment]
Yes, I've compiled that in release mode AFAIK.

**Pull request merged**
