### PR TITLE
RavenDB-4523 Typo: Enviroment -> Environment

### PR DESCRIPTION
**Pull request by ml054**

### CODE REVIEW

**Comment by ayende** [comment]
Can you fix the merge conflict?

**Comment by ml054** [comment]
Fixed.

**Comment by ayende** [comment]
Still  conflicting :-1: 
I think that this is because of the other PR I just merged

**Comment by ml054** [comment]
Please try again now. I'm sorry for troubles.

**Comment by ayende** [comment]
No worries :-)

**Pull request merged**
