### PR TITLE
RavenDB-4085 Export doesn't include documents created during the export

### PR DESCRIPTION
**Pull request by ppekrol**

### CODE REVIEW

**Comment by ppekrol** [comment]
@arekpalinski will do a review

**Comment by arekpalinski** [comment]
It looks good to me, however in `SmugglerDatabaseApiBase` there are missing `.ConfigureAwait(false)` calls.

**Comment by ppekrol** [comment]
@ayende I noticed that following tests are failing:
RavenDB_1603.CanDumpAttachmentsWithLimit_Dumper
RavenDB_1603.CanDumpAttachmentsWithLimit_Smuggler
RavenDB_1603.CanPerformDumpWithLimit_Dumper
RavenDB_1603.CanPerformDumpWithLimit_Smuggler

They fail because limit option can cause an export integrity issues. Not sure what the approach should be. We can mark the option as 'not-safe' or remove it. What do you think?

**Comment by HibernatingRhinosServiceAccount** [comment]
I'm not sure, what do you mean, export integrity issue on limit?

*Hibernating Rhinos Ltd  *

Oren Eini* l CEO l *Mobile: + 972-52-548-6969

Office: +972-4-622-7811 *l *Fax: +972-153-4-622-7811

**Comment by ppekrol** [comment]
We are performing exports in a loop and last export is using different mechanism that predecessors. It is opening a single transaction on server-side and downloading everything from etags that previous runs finished. This server-side run makes the export consistent, but limit option is interfering, because to make a export consistent I must download everything from the last run and limit would... limit it. This is why tests are failing.

**Comment by HibernatingRhinosServiceAccount** [comment]
We can say that we ignore the limit during that last phase, I guess.

*Hibernating Rhinos Ltd  *

Oren Eini* l CEO l *Mobile: + 972-52-548-6969

Office: +972-4-622-7811 *l *Fax: +972-153-4-622-7811

**Comment by ppekrol** [comment]
Hmm, but this way the limit will not work at all. E.g. I got 1000 documents and I set limit to 100, so first phase will download 100 and last phase will start from the point where first phase finished, so at the end it will download 900 documents.

**Comment by ayende** [comment]
Imagine that you get 50 docs, then go into the final mode.
You have another 100 docs there, but your limit is 100, so you get the next 50, and you are done.
User explicitly asked for this to happen.

If you got the 100 in the first case, no need to go into the 2nd stage

**Comment by ppekrol** [comment]
Done, waiting for tests.

**Pull request merged**
