### PR TITLE
RavenDB-4851 Ensure transaction lock fairness for flush.

### PR DESCRIPTION
**Pull request by fitzchak**

### CODE REVIEW

**Comment by ayende** [comment]
@redknightlois @arekpalinski can you review this as well please?

**Comment by arekpalinski** [comment]
This way we won't _ensure_ the lock fairness (by fairness I assume we'd like the waiters to acquire the lock in FIFO order). We are slowing down other competitors so we are promoting the flushing thread in an attempt to ask for the lock. For sure, it will attempt to acquire the lock a bit earlier. There are two scenarios then:

1) the lock isn't being currently taken (and no one is waiting) then the flushing thread indeed will get it because it's first
2) if there is a thread (or many threads) already waiting for the tx lock then slowing down others for 1ms won't make any difference because `Monitor.TryEnter` is not fair anyway. Effectively we won't ensure fairness then

Regarding unfairness of `Monitor.TryEnter`:
- http://stackoverflow.com/questions/4228864/does-lock-guarantee-acquired-in-order-requested
- http://www.developer.com/net/net/article.php/1580401

**Comment by arekpalinski** [comment]
However I'm not sure what was the goal of this change. Maybe 1st scenario is enough for us.

**Comment by ayende** [comment]
The idea isn't to actually ensure fairness.
The idea is to give the flushing thread a _chance_ to run.

Consider the following scenario, we have a high write scenario, and the tx merge is basically sitting there in a tight loop, running through the incoming transactions.
It creates a lot of work for the flushing thread, which need to run.
Now, the problem is that the tx merge thread is fast enough to release & acquire the lock before the tx merge thread can do that. And it does that in a loop.
Effectively, we starve out the flushing thread.

In this case, we let the flushing thread the priority boost (it won't be waiting) to get the lock first.
If there are competing threads on the lock, most of them would hit the sleep and lose, but even if they don't, the fact that the flushing thread isn't waiting, and that we broke the tight loop on acquire/release of the lock means that we have a high chance to give it to the flusher within the specified timeout.

**Comment by arekpalinski** [comment]
Okay, make sense. The only issue is the name `EnsureTransactionLockFairnessForFlush`, it's confusing. As you pointed we don't _ensure fairness_ but give the flushing thread _a chance_ to run.

**Pull request merged**
