### PR TITLE
RavenDB-12028 related change and RavenDB-12059 fix (WIP)

### PR DESCRIPTION
**Pull request by myarichuk**
Make sure graph query syntax in the form of "match (o:Orders (id() ='orders/825-A'))" work

### CODE REVIEW

**Comment by myarichuk** [comment]
Did *git pull* with rebase from v4.1 and got this huge amount of commits. Not sure why. 

The commits I wanted to merge are 
1) https://github.com/ayende/ravendb/pull/4680/commits/2492c317d06c132e96a7bffba0901079785a2969
2) https://github.com/ayende/ravendb/pull/4680/commits/abf136e6f247c2577ae8b28fb1ce2ec1306a480b

**Comment by ppekrol** [comment]
Let me help you...

**Comment by ppekrol** [comment]
Now good?

**Comment by myarichuk** [comment]
yeah, those commits are the ones I wanted in, thanks!

**Comment by myarichuk** [comment]
Another commit -> it is WIP, it only handles the parsing of graph queries that have the following syntax
*match (o:Orders (id() = 'orders/825-A'))-[:Lines[].Product]->(p:Products)*
(edge is an embedded object/embedded collection of the document)

**Comment by ayende** [comment]
Merged here: https://github.com/ayende/ravendb/tree/v4.2
Once I get the allocators done, I'll move this to `ravendb/ravedbn`

**Pull request closed without merging**
