### PR TITLE
RavenDB-3979 [v3.5]

### PR DESCRIPTION
**Pull request by arekpalinski**

### CODE REVIEW

**Comment by ayende** [comment]
Compilation failed on this

**Comment by arekais** [comment]
Indeed TeamCity reported "compilation failed", however the build log contains:`msbuild exit code: 0`.
Dnx projects compiled succesfully as well. I'm not sure why it reported that the compilation failed.

Additionally, just 2 tests failed (5342 passed). I've just scheduled the TC build once again.

**Comment by arekais** [comment]
Pawel has fixed some issue in TC build step / script (not sure exactly). The build is currently running.

**Comment by arekais** [comment]
Ready to merge. Just 2 tests failed (they pass on my machine). The fix I mentioned was made by Pawel is https://github.com/ayende/ravendb/pull/3058

**Pull request merged**
