### PR TITLE
Removed redundant condition _log.IsDebugEnabled

### PR DESCRIPTION
**Pull request by DamirAinullin**
Removing redundant condition _log.IsDebugEnabled

### CODE REVIEW

**Comment by HibernatingRhinosServiceAccount** [comment]
Hi!

Thank you for contributing into RavenDB project. Unfortunetely we detected that not all committers signed our CLA.

Following contributors are not in our database:
- DamirAinullin (damirainullin@outlook.com)

Please visit http://ravendb.net/contributors/cla/sign to sign CLA.

**Comment by DamirAinullin** [comment]
@ayende, cla/signed mechanism does not work. I see 500 error after clicked by link fom my email.
http://joxi.ru/zAN5k8eilGdyq2

**Comment by gregolsky** [comment]
@DamirAinullin , would you please try clicking on the link from the e-mail again?

**Comment by DamirAinullin** [comment]
@gregolsky , done.

**Comment by ayende** [comment]
Thanks, merged

**Pull request merged**
