### PR TITLE
Specified the link to download IIS Express v10.0 for using on the bui…

### PR DESCRIPTION
**Pull request by fitzchak**
…ld servers.

### CODE REVIEW

**Comment by ayende** [comment]
Do we have the build bot working now?

**Comment by ppekrol** [comment]
Yes, you can click on 'Details' to go to TC to view the build status

**Comment by ayende** [comment]
Can it add the link to that to github?

*Hibernating Rhinos Ltd  *

Oren Eini* l CEO l *Mobile: + 972-52-548-6969

Office: +972-4-622-7811 *l *Fax: +972-153-4-622-7811

**Comment by ayende** [comment]
Okay, I see that it does work this way, great.

*Hibernating Rhinos Ltd  *

Oren Eini* l CEO l *Mobile: + 972-52-548-6969

Office: +972-4-622-7811 *l *Fax: +972-153-4-622-7811



On Tue, Nov 3, 2015 at 1:17 PM, Oren Eini (Ayende Rahien) <ayende@ayende.com

**Comment by fitzchak** [comment]
Yes, it does. TeamCity can comment here when it starts the build and when it ends it with the build results, but it spam the comments, so we can see this same data when clicking on Details.

**Comment by ayende** [comment]
Okay

*Hibernating Rhinos Ltd  *

Oren Eini* l CEO l *Mobile: + 972-52-548-6969

Office: +972-4-622-7811 *l *Fax: +972-153-4-622-7811



On Tue, Nov 3, 2015 at 1:28 PM, Fitzchak Yitzchaki <notifications@github.com

**Pull request merged**
