### PR TITLE
Change index creation methods to execute all indexes in a single request

### PR DESCRIPTION
**Pull request by talweiss1982**
see http://issues.hibernatingrhinos.com/issue/RavenDB-3625

### CODE REVIEW

**Comment by ayende** [comment]
Why create a new project Raven.Tests.Misc?

**Comment by talweiss1982** [comment]
We didn't have a unit test for loading indexes from assembly.
The projects that do have indexes have too many of them (as i learned in my
first month trying to invoke this method on Test.Issues).
I could have added a .dll to issues but i thought it is better to have the
source code.

On Mon, Jul 6, 2015 at 7:15 AM, Ayende Rahien <notifications@github.com>
wrote:

> Why create a new project Raven.Tests.Misc?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ayende/ravendb/pull/2403#issuecomment-118708818>.
>



-- 

*Hibernating Rhinos Ltd  *[image: cid:image001.png@01CF95E2.8ED1B7D0]

Tal Weiss* l **Core Team Developer l *Mobile:+972-54-802-4849

Office: +972-4-622-7811* l *Fax: +972-153-4-622-7811*l* Skype: talweiss1982

*Raven**DB** paving the way to "Data Made Simple" http://ravendb.net/
<http://ravendb.net/> *

**Comment by ayende** [comment]
You can use the overload that accept a specific catalog:

IndexCreation.CreateIndexes(new CompositionContainer(new
AssemblyCatalog(Assembly.GetAssembly(typeof(TestStrIndex)))),
store.DatabaseCommands, new DocumentConvention());

*Hibernating Rhinos Ltd  *

Oren Eini* l CEO l *Mobile: + 972-52-548-6969

Office: +972-4-622-7811 *l *Fax: +972-153-4-622-7811

**Comment by ayende** [comment]
IndexCreation.CreateIndexes(new CompositionContainer(new
*TypeCatalog*(typeof(TestStrIndex)))),
store.DatabaseCommands, new DocumentConvention());

*Hibernating Rhinos Ltd  *

Oren Eini* l CEO l *Mobile: + 972-52-548-6969

Office: +972-4-622-7811 *l *Fax: +972-153-4-622-7811



On Mon, Jul 6, 2015 at 1:19 PM, Oren Eini (Ayende Rahien) <ayende@ayende.com

**Comment by talweiss1982** [comment]
Okay, i'll remove the project and do it like that.

On Mon, Jul 6, 2015 at 1:20 PM, Ayende Rahien <notifications@github.com>
wrote:

> IndexCreation.CreateIndexes(new CompositionContainer(new
> *TypeCatalog*(typeof(TestStrIndex)))),
> store.DatabaseCommands, new DocumentConvention());
>
> *Hibernating Rhinos Ltd *
>
> Oren Eini* l CEO l *Mobile: + 972-52-548-6969
>
> Office: +972-4-622-7811 *l *Fax: +972-153-4-622-7811
>
>
>
> On Mon, Jul 6, 2015 at 1:19 PM, Oren Eini (Ayende Rahien) <
> ayende@ayende.com
> > wrote:
>
> > You can use the overload that accept a specific catalog:
> >
> > IndexCreation.CreateIndexes(new CompositionContainer(new
> > AssemblyCatalog(Assembly.GetAssembly(typeof(TestStrIndex)))),
> > store.DatabaseCommands, new DocumentConvention());
> >
> > *Hibernating Rhinos Ltd *
> >
> > Oren Eini* l CEO l *Mobile: + 972-52-548-6969
> >
> > Office: +972-4-622-7811 *l *Fax: +972-153-4-622-7811
> >
> >
> >
> > On Mon, Jul 6, 2015 at 11:37 AM, talweiss1982 <notifications@github.com>
> > wrote:
> >
> >> We didn't have a unit test for loading indexes from assembly.
> >> The projects that do have indexes have too many of them (as i learned in
> >> my
> >> first month trying to invoke this method on Test.Issues).
> >> I could have added a .dll to issues but i thought it is better to have
> the
> >> source code.
> >>
> >> On Mon, Jul 6, 2015 at 7:15 AM, Ayende Rahien <notifications@github.com
> >
> >> wrote:
> >>
> >> > Why create a new project Raven.Tests.Misc?
> >> >
> >> > —
> >> > Reply to this email directly or view it on GitHub
> >> > <https://github.com/ayende/ravendb/pull/2403#issuecomment-118708818>.
> >> >
> >>
> >>
> >>
> >> --
> >>
> >> *Hibernating Rhinos Ltd *[image: cid:image001.png@01CF95E2.8ED1B7D0]
> >>
> >> Tal Weiss* l **Core Team Developer l *Mobile:+972-54-802-4849
> >>
> >> Office: +972-4-622-7811* l *Fax: +972-153-4-622-7811*l* Skype:
> >> talweiss1982
> >>
> >> *Raven**DB** paving the way to "Data Made Simple" http://ravendb.net/
> >> <http://ravendb.net/> *
> >>
> >> —
> >> Reply to this email directly or view it on GitHub
> >> <https://github.com/ayende/ravendb/pull/2403#issuecomment-118775537>.
> >>
> >
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ayende/ravendb/pull/2403#issuecomment-118800101>.
>



-- 

*Hibernating Rhinos Ltd  *[image: cid:image001.png@01CF95E2.8ED1B7D0]

Tal Weiss* l **Core Team Developer l *Mobile:+972-54-802-4849

Office: +972-4-622-7811* l *Fax: +972-153-4-622-7811*l* Skype: talweiss1982

*Raven**DB** paving the way to "Data Made Simple" http://ravendb.net/
<http://ravendb.net/> *

**Pull request merged**
