### PR TITLE
RavenDB-4308 cosmetic: added feature to use Raven-Entity-Label metadata for collection name display in HTML5 studio, to keep it separate from Raven-Entity-Name, which is used in other things.

### PR DESCRIPTION
**Pull request by ciel**
Added the functionality for a user to specify a "*Raven-Entity-Label*" metadata separate from entity name, which will be used in rendering collection labels to the screen in the HTML5 studio.

The label is retrieved by a simple transformer, *Raven/LabelsByCollectionName*. This transformer is created if it is not found when the collections view is rendered.

If an entity label is not found, the fallback default is to return to using Raven-Entity-Name, as expected.

This adds a new line to the editDocument.html view to display the Raven-Entity-Label if it is present.

http://issues.hibernatingrhinos.com/issue/RavenDB-4308

### CODE REVIEW

**Comment by ciel** [comment]
I'm still unclear about what "commit/message/conventions" refers to. I thought that was the referencing of an issue report, like I did?

**Comment by ppekrol** [comment]
commit/message/conventions checks if all commits in a PR contain the issue number, in your case your commit messages should be:
'RavenDB-4308 cosmetic: added feature to use Raven-Entity-Label metadata for collec…
…tion name display in HTML5 studio, to keep it separate from Raven-Entity-Name, which is used in other things.'

**Comment by ciel** [comment]
Okay. I've fixed the request name, I think.

**Comment by ppekrol** [comment]
I've meant commit message. not PR name. I suggest amending commit and doing a force push it iwll update PR accordingly.

**Comment by ciel** [comment]
Okay. Done.

**Comment by ciel** [comment]
Hrnm. I don't understand, I did the commit like you said but the conventions still failed.

**Comment by ppekrol** [comment]
Commit message is still the same: https://github.com/ciel/ravendb/commit/fc85b5948c07eaa2c09d4a61aa50749461a5cc0d

**Comment by ciel** [comment]
I'm sorry, I don't know how to change that.

**Comment by ppekrol** [comment]
No problem, someone will review your PR shortly and will make adjustments if necessary.

**Comment by ciel** [comment]
Thank you. I am sorry. I am going to read up on how to fix this for next time, but I think I'll avoid tampering with it right now.

**Comment by ciel** [comment]
simple push, fixed an error with async problems and made sure that the collections are sorted correctly.

**Comment by ppekrol** [comment]
@ml054 will review your PR

**Comment by ml054** [comment]
Okay. In order..

1. May I please have clarification about what you mean by "escaping"? I
think I understand now, but want to verify.

Escaping is used for lucene query syntax. See https://github.com/ayende/ravendb/blob/v3.5/Raven.Studio.Html5/App/common/queryUtil.ts#L11 

2. I'm not clear on where you're seeing " result.length === 0"

I'm not seeing this, because this check is missing. 

3. What's the best course here? Should I delete my pull request and make a
new one when the redesign is finished? It will have to be quite a bit
different after all.

I think we should close this PR and please open new once once you make necessary changes + please remember to set v3.5 as your branch to merge into.

**Pull request closed without merging**
