### PR TITLE
RavenDB-3960 Raven.Debug is not working when .NET 4.5.2 or 4.6 is ins…

### PR DESCRIPTION
**Pull request by ml054**
…talled

### CODE REVIEW

**Comment by ayende** [comment]
Note that we need to also change Raven.Debug so it will have better behavior when it can't attach properly

**Comment by ppekrol** [comment]
@ayende Can you describe in details what do you mean? How this behavior should look like?

**Comment by ayende** [comment]
Raven.Debug can't find dbengine.dll, or any error, really, it should NOT throw an unhandled exception.
Instead, it should write the full error details + diagnostics to the stderr, than quit with non zero code.

That way, when we run into issues, we won't have this:

image

**Comment by ppekrol** [comment]
Ohh, ok. Will handle this tomorrow.

**Pull request merged**
