### PR TITLE
Fix RavenDB-3978 Failing tests - Time Series

### PR DESCRIPTION
**Pull request by fitzchak**

### CODE REVIEW

**Comment by ppekrol** [comment]
@fitzchak Can you convert tabs to spaces in your commit?

**Comment by fitzchak** [comment]
@ppekrol Do we have a script that does that?

**Comment by ppekrol** [comment]
we have a script that will iterate through all files (7000), I will prepare something better

**Comment by fitzchak** [comment]
Great.

I'm closing this PR and will issue a new one, in order to test integration with TeamCity, which should test this PR.

**Comment by ppekrol** [comment]
Here is the script:
```
#!/bin/sh

against="$1"
files=`git --no-pager diff --name-only HEAD $against |
                       egrep '\.cs$|\.csproj$|\.vbproj$|\.fsproj$|\.dbproj$|\.ascx$|\.xaml$|\.cmd$|\.ps1$|\.coffee$|\.config$|\.css$|\.nuspec$|\.scss$|\.cshtml$|\.htm$|\.html$|\.js$|\.ts$|\.msbuild$|\.resx$|\.ruleset$|\.Stylecop$|\.targets$|\.tt$|\.txt$|\.vb$|\.vbhtml$|\.xml$|\.xunit$|\.java$|\.less$' |
                       uniq`

# Find files with trailing whitespace
for FILE in $files ; do
if [[ -e "$FILE" ]]; then
    echo "Fixing whitespace in $FILE"
    TMP="$FILE.tmp"
    expand --tabs=4 --initial "$FILE" > TMP
    mv TMP "$FILE"
    git add "$FILE"
fi
done
```

just save it as "normalize_pr.sh" in your repo and execute following command:
```
./normalize_pr.sh 25066b49c385c0a98ce4ef5d212ffa292c7c68b8
```

the 25066b49c385c0a98ce4ef5d212ffa292c7c68b8 is a latest commit hash from @ayende v3.5 branch,
then you can commit all normalized files

**Comment by fitzchak** [comment]
Done, thanks for the script!

**Pull request merged**
