### PR TITLE
RavenDB-4329 indexing base + auto indexes (WIP)

### PR DESCRIPTION
**Pull request by ppekrol**

### CODE REVIEW

**Comment by ppekrol** [comment]
@ayende we have moved notifications simultaneously, I just rebased my solution

**Comment by HibernatingRhinosServiceAccount** [comment]
I'm not sure that I like the number of transactions we now have.

* Voron.Impl.Transaction
* Voron.Impl.LowLevelTransaction
* RavenTransaction
* DocumentsTransaction

And then we have:

* MemoryOperationContext
* TransactionOperationContext<TTransaction>
* DocumentsOperationContext
* TransactionOperationContext

That is a lot of infrsatructure to have.

And the more storage engines we'll have, the more it will grow.

*Hibernating Rhinos Ltd  *

Oren Eini* l CEO l *Mobile: + 972-52-548-6969

Office: +972-4-622-7811 *l *Fax: +972-153-4-622-7811

**Comment by ppekrol** [comment]
@ayende We need to operate somehow on various entities in the database. I do not see a different way of doing this. The transaction needs to be resource-aware e.g. look at the notifications handling.

Putting everything in one bag will result in chaos and will cause maintenance difficulties in a long run.

**Comment by ayende** [comment]
I know that, but it seems like a lot of moving parts. And a lot of stuff
that we'll need to allocate / subtle differences.
Worth seeing if we can reduce this in some manner.
Maybe having a property for DatabaseTransactionStuff on the tx, instead?



*Hibernating Rhinos Ltd  *

Oren Eini* l CEO l *Mobile: + 972-52-548-6969

Office: +972-4-622-7811 *l *Fax: +972-153-4-622-7811

**Comment by ppekrol** [comment]
Wouldn't the 'DatabaseTransactionStuff' result in a same solution by the end. We will have to end up with various implementations and to access them we would need to do some casting or introduce a class with generic type.

**Comment by ayende** [comment]
No, just a bunch of properties on the Transaction class. No need for
casting / generics.

public class Tx
{
   public DatabaseStuff Database;
   public FileSystemStuff FileSystem;
}

*Hibernating Rhinos Ltd  *

Oren Eini* l CEO l *Mobile: + 972-52-548-6969

Office: +972-4-622-7811 *l *Fax: +972-153-4-622-7811

**Pull request merged**
