### PR TITLE
RavenDB-3759 and RavenDB-3979 [v4.0]

### PR DESCRIPTION
**Pull request by arekpalinski**

### CODE REVIEW

**Comment by ayende** [comment]
A lot of tests are now failing because of this?

**Comment by arekais** [comment]
Yes, I made a stupid mistake in the base class of file system tests. I will fix that and run TC build once again.

**Comment by arekais** [comment]
Tests fixed. However let's wait with merge until TC processes this pull request.

**Comment by arekais** [comment]
The is still a bunch of failing tests - looking into that.

**Comment by arekais** [comment]
Actually most tests failed because of configuration refactoring work - I just didn't notice that because previously 4.0 tests have timed out. TC build is running.

**Comment by ayende** [comment]
Still lots of failures

**Comment by arekais** [comment]
Yes, I'm tracking this. Just fixed tests of counters... however what bothers me more is that most tests is failing because of:

`System.IO.IOException : The following processes are locking C:\Builds\RavenDB-PR-Tests\Raven.Tests.Issues\bin\Release\Databases\System\0000000000000000000.journal
 xunit.console.clr4 2916`
 
 `System.UnauthorizedAccessException : Access to the path 'C:\Builds\RavenDB-PR-Tests\Raven.Tests.Issues\bin\Release\Databases\System\scratch.0000000000.buffers' is denied.
`

**Comment by ayende** [comment]
That is usually an indication that we didn't close the database and started
another.

*Hibernating Rhinos Ltd  *

Oren Eini* l CEO l *Mobile: + 972-52-548-6969

Office: +972-4-622-7811 *l *Fax: +972-153-4-622-7811

**Comment by aviviadi** [comment]
Is it by any chance related to http://issues.hibernatingrhinos.com/issue/RavenDB-4090 ?

**Comment by HibernatingRhinosServiceAccount** [comment]
I don't think so, that would just make us slow, no?

*Hibernating Rhinos Ltd  *

Oren Eini* l CEO l *Mobile: + 972-52-548-6969

Office: +972-4-622-7811 *l *Fax: +972-153-4-622-7811

**Comment by arekais** [comment]
I don't think so as well. It rather seems to me that we don't dispose something properly: either there is a test which does something really wrong (does not cleans up after itself when it faults?) or some bug in Voron. However that won't be easy to find - I cannot reproduce that locally.

**Comment by ayende** [comment]
Note that this is on the _system_ db, and most of our tests are actually
using a path based on the test name, not a generic one.

*Hibernating Rhinos Ltd  *

Oren Eini* l CEO l *Mobile: + 972-52-548-6969

Office: +972-4-622-7811 *l *Fax: +972-153-4-622-7811

**Comment by arekais** [comment]
Yes, I'm aware of that. However as you just said: "most of our tests". The good thing is that it just happened on my machine.

**Comment by arekais** [comment]
Take a look at: http://issues.hibernatingrhinos.com/issue/RavenDB-4167 to see what was the root of the problem.

**Pull request merged**
