### PR TITLE
RavenDB-4677 Fixing Voron schema updater (1.2 to 1.3)

### PR DESCRIPTION
**Pull request by arekpalinski**

### CODE REVIEW

**Comment by ayende** [comment]
Do we already have any valid users using schema 1.3?

**Comment by arekpalinski** [comment]
I don't know about any. Probably not since no one reported any problems after upgrading to it.

**Comment by ayende** [comment]
The reason I'm asking is that it might be better to actually create a new schema version, because if you area already on 1.3, we won't fix that.

**Comment by arekpalinski** [comment]
If you are already in 1.3 it means that you have index data migrated incorrectly and it's split into two tables e.g "by_view" and "scheduled_reductions_by_view", but we don't use records from the invalid one - "by_view". Also because of incorrect table names we used in the migrator, records in a single table can be different e.g. we had "scheduled_reductions_by_view" and "mapped_results_by_view" indexes but in result of the migration all their records were put into "by_view". I don't think we can do anything reasonable then.

**Pull request merged**
