### PR TITLE
properly respect AllowMultipleIndexEntriesForSameDocumentToResultTransformer flag for queries with transformers

### PR DESCRIPTION
**Pull request by myarichuk**
…

### CODE REVIEW

**Comment by ayende** [comment]
You have whitespace issues that needs fixing

**Comment by myarichuk** [comment]
I will check (thought that Pawel's tortoise git script should handle this)

**Comment by ayende** [comment]
I fixed it, but make sure to update your VS settings

*Hibernating Rhinos Ltd  *

Oren Eini* l CEO l *Mobile: + 972-52-548-6969

Office: +972-4-622-7811 *l *Fax: +972-153-4-622-7811

**Comment by ppekrol** [comment]
@myarichuk Can you check that you have it installed in your repository? It should be in .git/hooks/pre-commit

**Comment by myarichuk** [comment]
@ppekrol good catch, in that repository I didn't have it (I have two local repositories now, in case that I need to work on both 2.5 and other version)

**Pull request merged**
