### PR TITLE
Merge linux-mono from ayende

### PR DESCRIPTION
**Pull request by aviviadi**
Includes merge with what supposed to be similar to Master branch and:
1. Fix compilation issues of mono (ThreadLocal)
2. Remove MS dependencies (VB - TextFieldParser, AccountManagement - IsInRole in SpecificPlatform dll)
3. Handle LowMem in linux (sysinfo)
4. Fix "little" issues like : Directory permissions different in linux

Server now can be executed (with and without previous db existance).
Known problems : curl POST can be executed only once per session..

### CODE REVIEW

**Comment by aviviadi** [comment]
This is the complete changes of this pull request

**Comment by ayende** [comment]
Why was this closed?

**Comment by aviviadi** [comment]
I am new with git.... no reason to close it.

**Comment by aviviadi** [comment]
Open back the pull request

**Comment by aviviadi** [comment]
---------- Forwarded message ----------
From: Adi Avivi <adi@hibernatingrhinos.com>
Date: Thu, Dec 24, 2015 at 10:49 AM
Subject: Re: Vacation
To: "Oren Eini (Ayende Rahien)" <ayende@ayende.com>


Hi,
I need to do MRI this Saturday (I am sure I have nothing sever, but the
doctor insisted to do it).
I still can't come to work because of the pain. Hope it will be better by
Sunday.


On Wed, Dec 23, 2015 at 1:38 PM, Oren Eini (Ayende Rahien) <
ayende@ayende.com> wrote:

> Okay
>
> *Hibernating Rhinos Ltd  *
>
> Oren Eini* l CEO l *Mobile: + 972-52-548-6969
>
> Office: +972-4-622-7811 *l *Fax: +972-153-4-622-7811
>
>
>
> On Wed, Dec 23, 2015 at 7:10 AM, Adi Avivi <adi@hibernatingrhinos.com>
> wrote:
>
>> Hi. I need the day off today to see my doctor. I will update later if i
>> return tomorrow.
>>
>
>


-- 
Best regards,




*Adi Avivi*

RavenDB Core Team

Tel: 972-4-6227811

Fax:972-153-4-6227811

Email : adi@hibernatingrhinos.com


*Raven**DB** paving the way to "Data Made Simple" http://ravendb.net/
<http://ravendb.net/>  *



-- 
Best regards,




*Adi Avivi*

RavenDB Core Team

Tel: 972-4-6227811

Fax:972-153-4-6227811

Email : adi@hibernatingrhinos.com


*Raven**DB** paving the way to "Data Made Simple" http://ravendb.net/
<http://ravendb.net/>  *

**Pull request closed without merging**
