### PR TITLE
RavenDB-4115:

### PR DESCRIPTION
**Pull request by talweiss1982**
Adding OnBulkInsert changed event to DocumentDatabse and hookinh replciation task on that.

### CODE REVIEW

**Comment by ayende** [comment]
Please fix the whitespace issue

**Comment by talweiss1982** [comment]
I have tabs set as spaces those tabs came for the pull i did.
This means somebody didn't set their VS to have tabs as spaces

**Comment by ayende** [comment]
Can you fix the PR?

*Hibernating Rhinos Ltd  *

Oren Eini* l CEO l *Mobile: + 972-52-548-6969

Office: +972-4-622-7811 *l *Fax: +972-153-4-622-7811

**Comment by talweiss1982** [comment]
Fixed by Micharl PR https://github.com/ayende/ravendb/pull/2988

**Pull request closed without merging**
