### PR TITLE
added finalizer to CancellationTimeout

### PR DESCRIPTION
**Pull request by ppekrol**

### CODE REVIEW

**Comment by ayende** [comment]
This will never be called.
The timer contains a reference a lambda, that capture the this pointer.
So we won't ever finalize this.

*Hibernating Rhinos Ltd  *

Oren Eini* l CEO l *Mobile: + 972-52-548-6969

Office: +972-4-622-7811 *l *Fax: +972-153-4-622-7811

**Comment by ayende** [comment]
We need to have two instances here. One that is used by the timer, one that
is used by the calling code


*Hibernating Rhinos Ltd  *

Oren Eini* l CEO l *Mobile: + 972-52-548-6969

Office: +972-4-622-7811 *l *Fax: +972-153-4-622-7811



On Mon, Jun 8, 2015 at 3:47 PM, Oren Eini (Ayende Rahien) <ayende@ayende.com

**Comment by ppekrol** [comment]
Actually, now when I'm looking at this... do we need to Dispose timer from lambda? We should rely on CancellationTimeout Dispose only or in worst case on CancellationTimeout finalizer.

**Comment by ayende** [comment]
Hm... we can rely on the timout dispose / finalizer. Would still cause us
to capture the this pointer, need to send the cancelation token source to
the timer callback as a state

*Hibernating Rhinos Ltd  *

Oren Eini* l CEO l *Mobile: + 972-52-548-6969

Office: +972-4-622-7811 *l *Fax: +972-153-4-622-7811

**Pull request merged**
