### PR TITLE
Tweaked collections divider appearance.

### PR DESCRIPTION
**Pull request by JudahGabriel**
The collections divider stands out like a sore thumb. Toned down the color a bit so that it fits in with the rest of the Studio colors.

### CODE REVIEW

**Comment by ayende** [comment]
@JudahGabriel Can you send PRs for 3.5 and 4.0 as well?

**Comment by JudahGabriel** [comment]
Sure thing, will do.

**Comment by ppekrol** [comment]
@ayende and @JudahGabriel No need to PR 4.0, since there are no relevant changes in that version and Marcin is doing a lot of stuff in 3.5 currently. When 3.5 work will be finished he will overwrite the 4.0 Studio with 3.5 one.

**Comment by JudahGabriel** [comment]
OK. Thanks Pawel. I'll just send a PR For 3.5 then.

**Pull request merged**
