### PR TITLE
RavenDB-3370

### PR DESCRIPTION
**Pull request by redknightlois**

### CODE REVIEW

**Comment by redknightlois** [comment]
Added repro for RavenDB-3372

**Comment by ayende** [comment]
The problem is that we don't support document ids that are that large.

A document id is limited to 2K characters (and I think we can limit it to 1K in Voron)
When running this in Esent, we get:

System.ArgumentException: The key must be a maximum of 2,048 bytes in Unicode, 1,024 characters, key is:

**Comment by redknightlois** [comment]
On a second look it is not reproducing exactly the effect I am looking for. I am failing before the place where I should have. Will iterate over the test case to repro effectively.

**Comment by redknightlois** [comment]
Now we have an exact repro.

**Comment by ayende** [comment]
Okay, see my comments on the issue for the fix, I'll wait to pull it with
your changes.

*Hibernating Rhinos Ltd  *

Oren Eini* l CEO l *Mobile: + 972-52-548-6969

Office: +972-4-622-7811 *l *Fax: +972-153-4-622-7811

**Pull request merged**
