### PR TITLE
LZ4 with support for acceleration

### PR DESCRIPTION
**Pull request by redknightlois**
This is as good as I could get without JIT support to achieve improvements. Default value for acceleration is 1, therefore I havent modified the tradeoff used by the RavenDB code. We can now try to see if we can get better compression for small strings up to 2048 or with LZ4(acceleration=50) than with Smaz. Also we can tune other sources of typically uncompressible data with higher acceleration values to trade speed for ratio if needed.

### CODE REVIEW

**Comment by ayende** [comment]
Can you open JIT issues so we can see if we can get the accepted?

**Comment by ayende** [comment]
Oh, I see that you already did on some. 
Can you add them here, so we'll know what to track?

**Comment by redknightlois** [comment]
This is probably the most important of all them: https://github.com/dotnet/coreclr/issues/6024 . I worked around most of the others with VERY UGLY code.

**Comment by redknightlois** [comment]
Also remembered that this one is important too.
https://github.com/dotnet/coreclr/issues/5025

**Pull request merged**
