### PR TITLE
RavenDB-3116 Cannot restore another time when restore failed before

### PR DESCRIPTION
**Pull request by ml054**

### CODE REVIEW

**Comment by ayende** [comment]
Look at your code (AdminController), You don't have just a single restore
status.
Also, if there is an error, you are saving and then deleting (the Database
is the system database in this case).


 catch (Exception e)
                {
                    restoreStatus.State = RestoreStatusState.Faulted;
                    restoreStatus.Messages.Add("Unable to restore database
" + e.Message);

DatabasesLandlord.SystemDatabase.Documents.Put(RestoreStatus.RavenRestoreStatusDocumentKey,
null,
                               RavenJObject.FromObject(restoreStatus), new
RavenJObject(), null);
                    throw;
                }
                finally
                {

Database.Documents.Delete(RestoreInProgress.RavenRestoreInProgressDocumentKey,
null, null);
                }

*Hibernating Rhinos Ltd  *

Oren Eini* l CEO l *Mobile: + 972-52-548-6969

Office: +972-4-622-7811 *l *Fax: +972-153-4-622-7811

**Comment by ml054** [comment]
By default I set status to running. Before catch I set to completed and I set status to failed in catch. 

When requests parameters are wrong we respond with badrequest which is also theaded as failure. 

I don't append and delete to the same document. 

RestoreStatus.RavenRestoreStatusDocumentKey - here we have restore status with _list_ of messages. We never delete this document. 

RestoreInProgress.RavenRestoreInProgressDocumentKey - this is used for mutex restore and is removed after each restore.

**Comment by ayende** [comment]
Oh, okay.

*Hibernating Rhinos Ltd  *

Oren Eini* l CEO l *Mobile: + 972-52-548-6969

Office: +972-4-622-7811 *l *Fax: +972-153-4-622-7811

**Comment by ml054** [comment]
So I assume PR can be merged.

**Comment by ayende** [comment]
Yes

*Hibernating Rhinos Ltd  *

Oren Eini* l CEO l *Mobile: + 972-52-548-6969

Office: +972-4-622-7811 *l *Fax: +972-153-4-622-7811

**Pull request merged**
