### PR TITLE
 Support Postgres arrays in sql replication #653 

### PR DESCRIPTION
**Pull request by brunomlopes**
@fitzchak, here it is, as requested.

### CODE REVIEW

**Comment by fitzchak** [comment]
Thanks.

https://github.com/ravendb/ravendb/pull/653

**Comment by brunomlopes** [comment]
Is there a way to track when this will appear on an unstable build?

**Comment by fitzchak** [comment]
It should appear soon, build 35145 was started.

**Comment by brunomlopes** [comment]
Great, thanks

On Thu, Jul 7, 2016 at 3:01 PM, Fitzchak Yitzchaki <notifications@github.com

**Pull request merged**
