### PR TITLE
removed unnecessary dependency

### PR DESCRIPTION
**Pull request by thefringeninja**
No need to take a dependency on Spatial4n.Core.NTS in Raven.Abstractions.

### CODE REVIEW

**Comment by ayende** [comment]
Hi,
Do you have CLA with us? http://ravendb.net/contributing

*Hibernating Rhinos Ltd  *

Oren Eini* l CEO l *Mobile: + 972-52-548-6969

Office: +972-4-622-7811 *l *Fax: +972-153-4-622-7811

**Comment by thefringeninja** [comment]
Hey!

Sorry for the late reply; enterprise printer copier problem but I finally
got it scanned.

On Fri, Apr 24, 2015 at 7:58 AM, Ayende Rahien <notifications@github.com>
wrote:

> Hi,
> Do you have CLA with us? http://ravendb.net/contributing
>
> *Hibernating Rhinos Ltd *
>
> Oren Eini* l CEO l *Mobile: + 972-52-548-6969
>
> Office: +972-4-622-7811 *l *Fax: +972-153-4-622-7811
>
>
>
> On Thu, Apr 23, 2015 at 6:45 PM, João Bragança <notifications@github.com>
> wrote:
>
> > No need to take a dependency on Spatial4n.Core.NTS in Raven.Abstractions.
> > ------------------------------
> > You can view, comment on, or merge this pull request online at:
> >
> > https://github.com/ayende/ravendb/pull/2152
> > Commit Summary
> >
> > - removed unnecessary dependency
> >
> > File Changes
> >
> > - *M* Raven.Abstractions/Exceptions/InvalidSpatialShapeException.cs
> > <https://github.com/ayende/ravendb/pull/2152/files#diff-0> (3)
> > - *M* Raven.Abstractions/Raven.Abstractions.csproj
> > <https://github.com/ayende/ravendb/pull/2152/files#diff-1> (4)
> >
> > Patch Links:
> >
> > - https://github.com/ayende/ravendb/pull/2152.patch
> > - https://github.com/ayende/ravendb/pull/2152.diff
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/ayende/ravendb/pull/2152>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ayende/ravendb/pull/2152#issuecomment-95810456>.
>



-- 
Sent from my regular computer
http://twitter.com/thefringeninja
http://www.thefringeninja.com/

**Comment by ayende** [comment]
That is great, can you send it? I don't think we got it

*Hibernating Rhinos Ltd  *

Oren Eini* l CEO l *Mobile: + 972-52-548-6969

Office: +972-4-622-7811 *l *Fax: +972-153-4-622-7811

**Comment by thefringeninja** [comment]
Are you sure? I attached it as a PDF

On Fri, May 1, 2015 at 1:02 PM, Ayende Rahien <notifications@github.com>
wrote:

> That is great, can you send it? I don't think we got it
>
> *Hibernating Rhinos Ltd *
>
> Oren Eini* l CEO l *Mobile: + 972-52-548-6969
>
> Office: +972-4-622-7811 *l *Fax: +972-153-4-622-7811
>
>
>
> On Fri, May 1, 2015 at 11:43 AM, João Bragança <notifications@github.com>
> wrote:
>
>
> > Hey!
> >
> > Sorry for the late reply; enterprise printer copier problem but I finally
> > got it scanned.
> >
> > On Fri, Apr 24, 2015 at 7:58 AM, Ayende Rahien <notifications@github.com
> >
> > wrote:
> >
> > > Hi,
> > > Do you have CLA with us? http://ravendb.net/contributing
> > >
> > > *Hibernating Rhinos Ltd *
> > >
> > > Oren Eini* l CEO l *Mobile: + 972-52-548-6969
> > >
> > > Office: +972-4-622-7811 *l *Fax: +972-153-4-622-7811
> > >
> > >
> > >
> > > On Thu, Apr 23, 2015 at 6:45 PM, João Bragança <
> notifications@github.com
> > >
> > > wrote:
> > >
> > > > No need to take a dependency on Spatial4n.Core.NTS in
> > Raven.Abstractions.
> > > > ------------------------------
> > > > You can view, comment on, or merge this pull request online at:
> > > >
> > > > https://github.com/ayende/ravendb/pull/2152
> > > > Commit Summary
> > > >
> > > > - removed unnecessary dependency
> > > >
> > > > File Changes
> > > >
> > > > - *M* Raven.Abstractions/Exceptions/InvalidSpatialShapeException.cs
> > > > <https://github.com/ayende/ravendb/pull/2152/files#diff-0> (3)
> > > > - *M* Raven.Abstractions/Raven.Abstractions.csproj
> > > > <https://github.com/ayende/ravendb/pull/2152/files#diff-1> (4)
> > > >
> > > > Patch Links:
> > > >
> > > > - https://github.com/ayende/ravendb/pull/2152.patch
> > > > - https://github.com/ayende/ravendb/pull/2152.diff
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <https://github.com/ayende/ravendb/pull/2152>.
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/ayende/ravendb/pull/2152#issuecomment-95810456>.
> > >
> >
> >
> >
> > --
> > Sent from my regular computer
> > http://twitter.com/thefringeninja
> > http://www.thefringeninja.com/
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/ayende/ravendb/pull/2152#issuecomment-98077998>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ayende/ravendb/pull/2152#issuecomment-98100559>.
>



-- 
Sent from my regular computer
http://twitter.com/thefringeninja
http://www.thefringeninja.com/

**Comment by ayende** [comment]
Can you send it to support@ravendb.net directly?

*Hibernating Rhinos Ltd  *

Oren Eini* l CEO l *Mobile: + 972-52-548-6969

Office: +972-4-622-7811 *l *Fax: +972-153-4-622-7811

**Pull request merged**
