### PR TITLE
Avoid NRE error in dotnet restore

### PR DESCRIPTION
**Pull request by fitzchak**
RavenDB-4653 Migrate Raven.Client to .NET Core

### CODE REVIEW

**Comment by ppekrol** [comment]
There are 2 line changes in default.ps1, 3 commits (including merge) and no issue #. Is this really necessary?

**Comment by fitzchak** [comment]
Yes,    "Avoid NRE error in dotnet restore" commit solves an issue on the build server.

**Comment by ppekrol** [comment]
I know, but I'm asking about the others + lack of issue #

**Comment by fitzchak** [comment]
I added the issue #.

In regards to the first commit, it was already merged. Not sure why it is here again.

**Comment by ppekrol** [comment]
Because @ayende cherry-picked your commit, you should reset your repository to the state from ayende/ravendb/v3.5 and re-apply only last commit. And BTW, issue number should be in the commit message and not in the text of the PR - you know that.

**Comment by fitzchak** [comment]
Done that.

**Comment by ppekrol** [comment]
New PR: https://github.com/ayende/ravendb/pull/3946

**Pull request closed without merging**
