### PR TITLE
RDBQA-45 removed 'Raven/Http/AuthenticationSchemes', added 'AuthenticationScheme' to client conventions

### PR DESCRIPTION
**Pull request by ppekrol**

### CODE REVIEW

**Comment by ayende** [comment]
What are you actually doing here?

**Comment by ppekrol** [comment]
This is for Windows Auth tests on TC

**Comment by ppekrol** [comment]
@ayende Please do not merge this yet, @fitzchak  and I will test this PR on TC and when it will be working as expected then we will let you know that this can be merged.

**Comment by ayende** [comment]
can we merge  / close this?

**Comment by ppekrol** [comment]
There is some kind of a problem with your domain accounts. @fitzchak and I agreed to wait till Monday (for you) to sort this out.

**Comment by fitzchak** [comment]
The tests are passing now

**Pull request merged**
