### PR TITLE
Facet and Index creation on sharded document store fix

### PR DESCRIPTION
**Pull request by talweiss1982**
this commit includes fixes for:
http://issues.hibernatingrhinos.com/issue/RavenDB-3096
and
http://issues.hibernatingrhinos.com/issue/RavenDB-3071

### CODE REVIEW

**Comment by florisrobbemont** [comment]
Hi Ayende, will these pull requests (and https://github.com/ayende/ravendb/pull/1762) end up in a 2.5 nuget release? And if so, when can I expect them?

**Comment by ayende** [comment]
No, they are for 3.0

*Hibernating Rhinos Ltd  *

Oren Eini* l CEO l *Mobile: + 972-52-548-6969

Office: +972-4-622-7811 *l *Fax: +972-153-4-622-7811

**Comment by florisrobbemont** [comment]
That's going to be a problem for us unfortunately. We use a single instance RavenDB 2.5 server for our production environment. Upgrading this is currently not an option. We cannot use the 3.0 client to connect to a 2.5 server, but we still need these fixes. 

Is there a way we could merge these fixes into a 'maintenance only' branch of 2.5. I suspect there might be more fixes in the future that affect the 2.5 product line.

**Comment by ayende** [comment]
Hi,
We're looking into what would be involved in back porting this, please give
us a couple of days to check it out

*Hibernating Rhinos Ltd  *

Oren Eini* l CEO l *Mobile: + 972-52-548-6969

Office: +972-4-622-7811 *l *Fax: +972-153-4-622-7811

**Comment by talweiss1982** [comment]
Hi Floris,
Are you also expecting to get the changes regarding AsynIndexCreation or are you only referring to wrong id and facet on sharded environment issues?

**Comment by florisrobbemont** [comment]
Hi @talweiss1982,

If possible, please add all these fixes to the 2.5 branch. As I said earlier, upgrading to 3.0 is not possible for us right now (we are planning to though).

Thnx

**Pull request merged**
