### PR TITLE
Removed part of condition which is always true

### PR DESCRIPTION
**Pull request by DamirAinullin**
Removed part of condition which is always true

### CODE REVIEW

**Comment by ayende** [comment]
What make you think that this is always true? And what does this gain us?

**Comment by DamirAinullin** [comment]
@ayende Because List<>Count can not be less 0. It can be only 0 or more by design of List<>. So I think it is useless condition and should be removed.

**Comment by ayende** [comment]
You missing it being equal to zero? Which is a valid condition here.

**Comment by DamirAinullin** [comment]
I did not. It can be only 0 or more. So we don't need to check if Count >= 0.

**Comment by ayende** [comment]
Look at your PR, you removed the condition:
image

**Comment by DamirAinullin** [comment]
@ayende I removed part of condition which is always true. Count can be 0 or more then 0. It can not be less 0. So condition List.Count >=0 is always useless because is always true. Why do you think it is not so? Your condition is equal next: if (result != null && result.Documents != null && true). I just removed last true.

**Comment by HibernatingRhinosServiceAccount** [comment]
Because it can be zero, in which case it matches, and fall into the if.
You removed the == 0 part

*Hibernating Rhinos Ltd  *

Oren Eini\* l CEO l *Mobile: + 972-52-548-6969

Office: +972-4-622-7811 *l *Fax: +972-153-4-622-7811

**Comment by DamirAinullin** [comment]
@ayende But in my case if Count == 0 then all condition will be true as previously. I am sure in it.

**Pull request closed without merging**
