### PR TITLE
Optimizations

### PR DESCRIPTION
**Pull request by redknightlois**

### CODE REVIEW

**Comment by ayende** [comment]
A lot of tests are failing now, probably because of this. I'm running all
of them on the master branch without this change.
Note that you need to run the Voron tests to see the failure.

*Hibernating Rhinos Ltd  *

Oren Eini* l CEO l *Mobile: + 972-52-548-6969

Office: +972-4-622-7811 *l *Fax: +972-153-4-622-7811

**Comment by redknightlois** [comment]
Hold it, somewhere along the line there is a difference. That makes 2 tests to fail.

**Comment by redknightlois** [comment]
Based on how I was checking consistency, I would have never catched this one (changing my tryout code to account for that). When changing the InnerBulkCopyMT to use StdLib.memcpy, I forgot to change the order of the parameters.

**Comment by ayende** [comment]
Won't pull, see discussion in issue.

**Pull request closed without merging**
