### PR TITLE
Changes API bug fix

### PR DESCRIPTION
**Pull request by grisha-kotler**

### CODE REVIEW

**Comment by ppekrol** [comment]
@grisha-kotler No need for 3.5 PR if you submitted fix to 3.0 and there are no 3.5 changes that would require different solution. We are still doing 3.0 to 3.5 merges.

**Comment by grisha-kotler** [comment]
OK.
In this case there were tests for counters only for 3.5.

**Comment by ayende** [comment]
Do we need to merge this, or not?

**Comment by ppekrol** [comment]
Yes, please merge this (it differs a bit). I will resolve conflicts manually during 3.0 to 3.5 merge.

**Pull request merged**
