### PR TITLE
New versioning bundle

### PR DESCRIPTION
**Pull request by fitzchak**
Ready to merge, without the subscription PR.

### CODE REVIEW

**Comment by fitzchak** [comment]
I see now that there are failing tests, probably because of bad re-applying of code, please wait with the merge.

**Comment by fitzchak** [comment]
Tests are passing. Ready to merge.

**Comment by ayende** [comment]
This has failing tests, closing for now until fixed.

**Comment by ayende** [comment]
- VersioningStorage.Log isn't used
- VersioningStorage._database isn't used
- Need comment explaining the use of the record separator
- What happens if the versioning configuration is corrupt? It will throw an error during db init, and then we can't fix it because we can't load the db.
- GetSliceFromKey allocates a buffer needlessly, should use a pooled buffer
- VersioningStorage shouldn't implement disposable

**Comment by ayende** [comment]
This has merge conflicts with the current version.
I merged it and it has failing tests, I pushed to your branch so you can look at exactly why this is happening.

**Comment by fitzchak** [comment]
Fixed the tests, there are two more failing tests which are related to a missing parameter in the replication endpoint:

http://issues.hibernatingrhinos.com/issue/RavenDB-4655

**Comment by fitzchak** [comment]
In regards to GetSliceFromKey GetBytes is reading and writing to a pointer. Please review this again.

**Comment by fitzchak** [comment]
Added expiration bundle.

**Pull request merged**
