### PR TITLE
[v4.0] - Bug fix - missing "CiHost" connection string in app.config of Raven.T…

### PR DESCRIPTION
**Pull request by fitzchak**
…ests.Bundles causes the SQL Replication tests to be skipped

### CODE REVIEW

**Comment by fitzchak** [comment]
Another fix was added to this PR

**Comment by ppekrol** [comment]
Should this be merged? Asking because TC is rescheduling tests for this from time to time.

**Comment by ayende** [comment]
I'm not sure that I understand what you mean?

*Hibernating Rhinos Ltd  *

Oren Eini* l CEO l *Mobile: + 972-52-548-6969

Office: +972-4-622-7811 *l *Fax: +972-153-4-622-7811

**Comment by ppekrol** [comment]
@ayende 
TeamCity is checking that the base for PR has changed and is rescheduling all 4 checks, which is good, but after 1 week it has run 7 times each check (cla/whitespace/conventions/tests).

This is why I asked if (maybe) you forgot to merge and close this PR.

**Comment by ayende** [comment]
Yes, I did forget :-)

**Pull request merged**
