### PR TITLE
added functionality to resize collections list.

### PR DESCRIPTION
**Pull request by ciel**
Added the ability to resize the collections list, and implemented it as a knockout binding handler appropriately.

The resizing will naturally keep the documents view sized correctly.

Additionally, fixed an issue with inconsistent scrollbars that was sometimes leading to errors on UI load.

Demonstration of this feature can be seen here: https://drive.google.com/file/d/0B7spg3aCB00dODhFV05kUkJmQWs/view

### CODE REVIEW

**Comment by ciel** [comment]
UPDATE: For some reason, my capture software doesn't show the resize cursor, but I assure you it is there as requested.

**Comment by ciel** [comment]
I'm not sure what commit/whitespace means.

**Comment by ppekrol** [comment]
Out script detected tabs in your commit:

[18:17:49][Step 1/1] Processing 'Raven.Studio.Html5/App/common/enableResizeBindingHandler.ts'
[18:17:49][Step 1/1] Processing 'Raven.Studio.Html5/App/viewmodels/documents.ts'
[18:17:49][Step 1/1] Processing 'Raven.Studio.Html5/App/viewmodels/shell.ts'
[18:17:49][Step 1/1] Processing 'Raven.Studio.Html5/App/views/documents.html'
[18:17:49][Step 1/1] Processing 'Raven.Studio.Html5/Content/app.css'
[18:17:49][Step 1/1] Detected tabs in 'Raven.Studio.Html5/Content/app.css'
[18:17:49][Step 1/1] Processing 'Raven.Studio.Html5/Content/app.less'
[18:17:50][Step 1/1] Detected tabs in 'Raven.Studio.Html5/Content/app.less'
[18:17:50][Step 1/1] Processing 'Raven.Studio.Html5/Content/app.min.css'
[18:17:50][Step 1/1] Processing 'Raven.Studio.Html5/Raven.Studio.Html5.csproj'

**Comment by ciel** [comment]
Okay. I will fix this.

**Comment by ciel** [comment]
Alright. I have made the fixes.

**Comment by ciel** [comment]
I'm not sure if the tests need to run or not. According to this post, Ayende said they don't usually run the tests for UI stuff : https://groups.google.com/d/msg/ravendb/XlfVUSMsLOI/Cdo6KkqqCgAJ

Just making a note in case they fail again.

**Pull request merged**
