### PR TITLE
RavenDB-4482

### PR DESCRIPTION
**Pull request by redknightlois**
Voron now supports page sizes of 4Kb, 8Kb, 16Kb and 32Kb.

### CODE REVIEW

**Comment by ppekrol** [comment]
@redknightlois can you fix whitespace issues? You are pushing tabs to the repository.

You can execute this https://github.com/ayende/ravendb/blob/v4.0/git_setup.cmd it will help with future commits. This one needs to be fixed manually though.

Here are your tabs:
Detected tabs in 'test/FastTests/Voron/ScratchBuffer/ScratchCanForceToFlushOldPages.cs'
Detected tabs in 'test/FastTests/Voron/Trees/TreeStateTests.cs'

**Comment by redknightlois** [comment]
Strange because I have Visual Studio set for insert spaces, not tabs (just checked)..

**Comment by redknightlois** [comment]
Fixed whitespaces and squashed commit.

**Comment by ppekrol** [comment]
Thanks, but it looks like the main problem is that both of those files contained tabs before you made your changes (probably from previous commits). Ignore it, I will normalize it next week.

**Comment by ayende** [comment]
Previously, slow tests:

**Comment by redknightlois** [comment]
Mhhh.. Are you sure that's the impact of only this PR? I dont think the change from CRC to xxHash64 would have that much of an impact.

**Comment by ayende** [comment]
Nope, not related. Probably an issue with the execution order of the test resulting in better perf.

**Pull request merged**
