### PR TITLE
RavenDB-3628 when we hit out of memory during indexing, then we should disable index and move on + voron will dynamically increase max scratch size

### PR DESCRIPTION
**Pull request by ppekrol**

### CODE REVIEW

**Comment by ayende** [comment]
Okay, the question is what do we do here.
The scratch space will be increased, without any limits, until we run out of disk space.
I'm not sure that I like this approach.

If we just dynamically increase the limit, what is the meaning of that limit in the first place?
I think that we would need to do this:

- When storage tells us the max ver pages is out, or scratch page is out, during indexing.
- We'll reduce the size of the batch we are running, and then retry. this way, there is a much bigger chance that we'll actually be able to proceed.
- This should apply to both map & reduce. And increasing the batch should be twice as hard, in order to avoid it.

I merged the first two commits, but not the third: "	when voron is used then we want to dynamically increase MaxScratchBuf… …"

**Comment by redknightlois** [comment]
The issue he is that we are faulting potentially a lot of processing because we have an arbitrary max size (hard knob). I would allow to dynamically grow the scratch buffer but signal a throttling. That has two side effects (both positive). The hard knob doesn't exist anymore, therefore there is no induced fault and wasted processing. And also it signals tavern to be more efficient for the current data layout without much effort. 

I am all in to kill all hard knobs when possible and convert them to suggestions. The end play is total auto configuration along the road.

**Comment by redknightlois** [comment]
Moreover it is ok to have a default for the 90% but penalizing the other 10% is risky as a product directive. More when those defaults imply a failure scenario.

**Comment by ayende** [comment]
So how about we _don't_ do this with exception handling?
Let us setup the RavenDB scratch file default to be very high. 6GB or
something like that.
But have it raise an event whenever it crosses a 512 MB boundary.

that would be the signal for us to reduce it, but we won't have the error
handling there.

*Hibernating Rhinos Ltd  *

Oren Eini* l CEO l *Mobile: + 972-52-548-6969

Office: +972-4-622-7811 *l *Fax: +972-153-4-622-7811

**Pull request closed without merging**
