### PR TITLE
RavenDB-4235 Fixing the issue that documents matching the selected in…

### PR DESCRIPTION
**Pull request by arekpalinski**
…dex or collection haven't appeared on Patch page.

http://issues.hibernatingrhinos.com/issue/RavenDB-4235

@ciel - can you take a look at this fix, because it reverses your change introduced in 09af1397be5a296fa2ec05af8be50d655bf0acaa

However it doesn't seem to influence the resizing a collections list feature.

### CODE REVIEW

**Comment by ciel** [comment]
I'm not quite sure what you're asking me to do.

**Comment by arekpalinski** [comment]
The question is why did you add `overflow-y: scroll;` which I removed in the commit of this PR.

**Comment by ciel** [comment]
I added it because the scroll bar was inconsistent. It's fine to remove
that, though.

**Comment by arekpalinski** [comment]
Okay. Thanks. 

Ready to merge.

**Comment by ciel** [comment]
Sorry for the confusion. This is my first pull request!

**Comment by arekpalinski** [comment]
No problem :) Thank you for contributing to RavenDB

**Pull request merged**
